services:
  - type: web
    name: fastapi-embed-server
    env: python
    region: Singapore
    plan: free  # Change to "starter" if Redis needed
    envVars:
      - key: REDIS_HOST
        value: relieved-jaybird-48846.upstash.io
      - key: PORT
        value: 8000
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
